config/routes.rb
Rails.application.routes.draw do
  resources :coffee_roasts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coffee_roast.rb
class CoffeeRoast < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coffee_roasts_controller.rb
class CoffeeRoastsController < ApplicationController
  before_action :set_coffee_roast, only: %i[ show edit update destroy ]

  # GET /coffee_roasts or /coffee_roasts.json
  def index
    @coffee_roasts = CoffeeRoast.all
  end

  # GET /coffee_roasts/1 or /coffee_roasts/1.json
  def show
  end

  # GET /coffee_roasts/new
  def new
    @coffee_roast = CoffeeRoast.new
  end

  # GET /coffee_roasts/1/edit
  def edit
  end

  # POST /coffee_roasts or /coffee_roasts.json
  # POST /coffee_roasts
  def create
    @coffee_roast = CoffeeRoast.new(coffee_roast_params)

    respond_to do |format|
      if @coffee_roast.save
        message = "The coffee roast '#{@coffee_roast.roast_name}' was just added."
        TwilioTextMessenger.new(message).call
        format.html { redirect_to @coffee_roast, notice: 'Coffee roast was successfully created.' }
        format.json { render :show, status: :created, location: @coffee_roast }
      else
        format.html { render :new }
        format.json { render json: @coffee_roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffee_roasts/1 or /coffee_roasts/1.json
  def update
    respond_to do |format|
      if @coffee_roast.update(coffee_roast_params)
        format.html { redirect_to coffee_roast_url(@coffee_roast), notice: "Coffee roast was successfully updated." }
        format.json { render :show, status: :ok, location: @coffee_roast }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coffee_roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffee_roasts/1 or /coffee_roasts/1.json
  def destroy
    @coffee_roast.destroy

    respond_to do |format|
      format.html { redirect_to coffee_roasts_url, notice: "Coffee roast was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_roast
      @coffee_roast = CoffeeRoast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_roast_params
      params.require(:coffee_roast).permit(:roast_name, :roast_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_roasts_helper.rb
module CoffeeRoastsHelper
end

app/views/coffee_roasts/_coffee_roast.html.erb
<div id="<%= dom_id coffee_roast %>">
  <p>
    <strong>Roast name:</strong>
    <%= coffee_roast.roast_name %>
  </p>

  <p>
    <strong>Roast description:</strong>
    <%= coffee_roast.roast_description %>
  </p>

</div>

app/views/coffee_roasts/_form.html.erb
<%= form_with(model: coffee_roast) do |form| %>
  <% if coffee_roast.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coffee_roast.errors.count, "error") %> prohibited this coffee_roast from being saved:</h2>

      <ul>
        <% coffee_roast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :roast_name, style: "display: block" %>
    <%= form.text_field :roast_name %>
  </div>

  <div>
    <%= form.label :roast_description, style: "display: block" %>
    <%= form.text_area :roast_description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coffee_roasts/edit.html.erb
<h1>Editing coffee roast</h1>

<%= render "form", coffee_roast: @coffee_roast %>

<br>

<div>
  <%= link_to "Show this coffee roast", @coffee_roast %> |
  <%= link_to "Back to coffee roasts", coffee_roasts_path %>
</div>

app/views/coffee_roasts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Coffee roasts</h1>

<div id="coffee_roasts">
  <% @coffee_roasts.each do |coffee_roast| %>
    <%= render coffee_roast %>
    <p>
      <%= link_to "Show this coffee roast", coffee_roast %>
    </p>
  <% end %>
</div>

<%= link_to "New coffee roast", new_coffee_roast_path %>

app/views/coffee_roasts/new.html.erb
<h1>New coffee roast</h1>

<%= render "form", coffee_roast: @coffee_roast %>

<br>

<div>
  <%= link_to "Back to coffee roasts", coffee_roasts_path %>
</div>

app/views/coffee_roasts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coffee_roast %>

<div>
  <%= link_to "Edit this coffee roast", edit_coffee_roast_path(@coffee_roast) %> |
  <%= link_to "Back to coffee roasts", coffee_roasts_path %>

  <%= button_to "Destroy this coffee roast", @coffee_roast, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twilloapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>